### ISSUE TITLE
Why use a Backend?

### ISSUE THREAD

**Issue by SeeHashTag90** [username-is-required/reddark#113]
Hi,

Can someone enlighten me on why every fork is using a backend?
I thought all the backend is doing is:

- Request a .json file that has all the subreddits.
- Relay said .json file to the frontend
- Frequently check whether there are updates and if so relay them to the frontend via websockets.

I only skimmed the code, so I might be missing something.

**Comment by username-is-required** [comment]
yeah, that’s pretty much right. the gist of what the backend does is: (1) load in the json file containing the list of subreddits (and refresh it every hour in case of any updates), (2) repeatedly (and very quickly) send requests to a reddit api endpoint to obtain the current status of those subreddits, and (c) when there’s an update to a subreddit’s status, relay it via socket.io to the connected clients. (there are some other features implemented in the backend code, such as [subreddit alert autofiltering](https://github.com/username-is-required/reddark/pull/106) and the ability to [trigger client refreshes when the frontend code is updated](https://github.com/username-is-required/reddark/blob/8a5b770128bfc1662d2ec7a6ec70dcce11adebed/main.js#L416-L422), but the gist of what the backend does is what i’ve said above.)

i’ll admit to being slightly confused by your question as to why the repo uses a backend. my question back would be, why *shouldn’t* it use a backend? to make one argument, if all of the repeated subreddit status checking was moved onto the front-end (to be performed by the clients rather than a server), not only would the number of api requests (to reddit) for the same number of clients increase massively (with each client having to make its own identical api requests), i would doubt that clients’ web browsers would be able to handle the sheer amount of api requests currently being made by the backend without a substantial and noticeable effect on performance on the client-side.

in addition, with the compute power & networking speeds typically available to a backend server (but not to most clients), i think it’s probably fair to say that the code making the repeated api requests would run much more efficiently on a typical backend server than locally on a client’s pc. it would also seem more efficient to me to have a server repeatedly making api requests and then relaying any changes, rather than forcing every client to make the same api requests themselves.

it’s possible that i might have misunderstood what you were asking, so let me know if so. if i have misunderstood what you’re asking, i apologise.

**Comment by SeeHashTag90** [comment]
> (2) repeatedly (and very quickly) send requests to a reddit api endpoint to obtain the current status of those subreddits.

Oops, I totally forgot that we are fetching the status of each subreddit and not just the big index.json file.

I agree it's a confusing question now that I understood the code better. Thanks for the response though!

**Comment by username-is-required** [comment]
no problem! glad to help
