### ISSUE TITLE
Possible enhancement - archived subreddits

### ISSUE THREAD

**Issue by robertafreese** [username-is-required/reddark#141]
I wanted to highlight the project here 
https://github.com/ArthurHeitmann/reddit_site_stats
https://blackout.photon-reddit.com/

to mention that perhaps as an enhancement to support all of these statuses: restricted, private, public, archived.

Some of the subs on the list in the sticky issue username-is-required/reddark-subinfo#146 are archived now and have all of the status options supported might be an enhancement to consider. 

From the linked production site,
![image](https://github.com/username-is-required/reddark-subinfo/assets/58523218/f7a6ed7e-6d88-4c3d-97b2-6ca1a740c3b5)

**Comment by username-is-required** [comment]
actually i think i changed my mind a little bit, and i’ve now changed the wording from ‘mods purged’ to ‘archived’. i did this because it occurred to me that - while a sub being ‘archived’ is a pretty good sign of a purged modteam, reddit admins can purge a modteam *without setting the sub to archived* (as seems to have happened with r/longhair). 

i therefore didn’t want any potential (false) implication that the subs displaying ‘mods purged’ are the *only* subs with purged mods, so i changed the status wording to ‘archived’.
